### ISSUE TITLE
Creating the Wiki

### ISSUE THREAD

**Issue by DonnyCraft1** [vbe0201/Shitcord#14]
### Describe the solution you'd like

I thought it would be nice to create a GitHub Wiki for this repo.

### Describe alternatives you've considered

I'm just wondering what plans you have about documentation.

### Additional Context

What a *~shit~* great question! Sure i have a good answer for that!

*~Just trying to use the same language as you guys.. 🥇 lol.~*

**Comment by byWambo** [comment]
Hm. This isn't such a bad idea, but i think that this library is just a bit completed and much things will get changed. I will ask the other developer.

**Comment by DonnyCraft1** [comment]
True.
But I would like to help to document when It's a little more finished since I'm probably not qualified for contributing to the source code. Python isn't my strongest language.

**Comment by G3bE** [comment]
There are [docs](https://shitcord.readthedocs.io/en/async/) now. So I guess this can be closed now.

**Comment by DonnyCraft1** [comment]
Closing the issue
